blog/urls.py
from django.urls import path
from . import views


app_name ='blog'
urlpatterns = [
    path('',views.all_blogs,name='all_blogs'),
    path('<int:blog_id>',views.detail,name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.indexpage,name='indexpage'),
    path('blog/', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls'))
]

urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor.fields import RichTextField


class BlogModel(models.Model):

    blog_title = models.CharField(max_length=30)
    blog_time = models.DateTimeField(auto_now_add=True)
    # image = models.ImageField(upload_to='blog/images/', default=False)
    blog_description = RichTextUploadingField()

    def __str__(self):
        return self.blog_title
    


    

 

portfolio/models.py
from django.db import models

class Project(models.Model):

    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)


    def __str__(self):
        return self.title
    

class MessageModel(models.Model):

    name = models.CharField(blank=False,max_length=20)
    email = models.EmailField(blank=False)
    message = models.TextField(blank=False,max_length=100)
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

portfolio/forms.py
from django.forms import ModelForm
from portfolio.models import MessageModel

class NewMessages(ModelForm):
    class Meta:
        model = MessageModel

        fields = '__all__'

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import BlogModel
from django.core.paginator import Paginator

def all_blogs(request):
    blogmodelobjects = BlogModel.objects.order_by('-blog_time')
    paginator = Paginator(blogmodelobjects,5)

    page = request.GET.get('page')

    blogmodelobjects = paginator.get_page(page)



    return(render(request,'blog/all_blogs.html',{'blogobjects':blogmodelobjects}))


def detail(request, blog_id):
    blog= get_object_or_404(BlogModel,pk = blog_id)
    return(render(request,'blog/detail.html',{'blog':blog}))

portfolio/views.py
from django.shortcuts import render
from . models import Project
from .forms import NewMessages



# Create your views here.
def indexpage(request):
    
    form = NewMessages
    projects = Project.objects.all()
    if(request.method =='POST'):
        form = NewMessages(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return(render(request,'portfolio/new.html',{'projects':projects,'form':form}))
    return(render(request,'portfolio/home.html',{'projects':projects,'form':form}))
    



    

blog/templates/blog/all_blogs.html
{% extends "portfolio/base.html" %}

{% block content %}

<h1 style="font-size:50px;" id="blogtitle" class="font-weight-bold text-center">ചിതലിനും വേണ്ടാത്ത കുറിപ്പുകൾ</h1>

<!-- <h3 style="font-size: small;" class="text-left mb-5">{{ blogobjects.paginator.count }} കുറിപ്പുകൾ</h3> -->
<div class="container" >
  <div class="jumbotron" >
{% for obj in blogobjects  %}
    <div class="row justify-content-center my-3">
     <div class="col-md-10">

   <a style="font-size: larger;" href="{% url 'blog:detail' obj.id %}"> <h3>{{ obj.blog_title }}</h3></a>
   
   <h5 class="text-muted"> {{ obj.blog_time| date:'d M Y' }}</h5>
    <h6>{{ obj.blog_description|striptags|truncatechars:100 |safe }}</h6>
</div>
</div>
{% endfor %}
</div>
</div>

<nav aria-label="...">
  <ul  class="pagination pagination-lg justify-content-center">

  {% for num in blogobjects.paginator.page_range %}

        <li  class="page-item"><a style="color:rgb(12, 12, 12);" class="page-link" href="?page={{ num }}">{{ num }}</a></li>
               
  {% endfor %}
</ul>

</nav>


{% endblock content %}

blog/templates/blog/detail.html
{% extends "portfolio/base.html" %}

{% block content %}
  


<h1 class="text-center mt-5" id="blogdetailtitle">{{ blog.blog_title }}</h1>
<h5 class="text-center text-muted mb-5">{{ blog.blog_time|date:'jS F Y' }}</h5>
<!-- <img class="text-center img-fluid mb-2" src="{{ blog.image.url }}" alt="" width="500" height="600"> -->


{{ blog.blog_description|safe }}


{% endblock content %}

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <link href="https://fonts.googleapis.com/css2?family=Grenze+Gotisch:wght@500;600;700&display=swap" rel="stylesheet"> 
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">

  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

  <link rel="icon" type="image/png" href="{% static "portfolio/index.png" %}">

  <title>Escapades</title>
</head>



<body>

    <nav id="topNav" class="navbar navbar-expand-md navbar-light">
      <div class="container">
        <a id="logo" class="navbar-brand" href="{% url 'indexpage' %}">
          <img src="{% static "portfolio/Escapades-PNG.png" %}" width="50" height="50" class="d-inline-block align-center" alt="Nick's Logo">
          <span>Escapades</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        
         
       
        <div class="collapse navbar-collapse text-center" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% static "portfolio/AmalBabuS_Resume.pdf" %}">Resume</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://www.facebook.com/anandu.raj.180" target="_blank">Facebook</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://www.instagram.com/sesky_sanyaasi/" target="_blank">Instagram</a>
            </li>
            
          </ul>
        </div>
      </div>
      <a role="button" href="{% url 'blog:all_blogs' %}" class="btn btn-primary">കുറിപ്പുകൾ</a>
    </nav>



<div class="container">

{% block content %}
  
{% endblock content %}
</div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends "portfolio/base.html" %}

{% block content %}
  
    {% load static %}
    <div class="row justify-content-center my-3">
        <div class="col-5">
          <img  src="{% static 'portfolio/index.png' %}" class="img-fluid">
        </div>
      </div>


      <div class="row justify-content-center mb-3">
        <div class="col-md-9 text-center">
          <style>
             .blink_me {
           animation: blinker 3s linear infinite;
            }

        @keyframes blinker {
            50% {
         opacity: 0;
        }
          }
          </style>
    
    <div class="blink_me"> <h5 id="hometext" class="font-weight-bold">എന്റെ മനസ്സൊരു നാടകവേദിയാണ്.. പഴയ ഓർമ്മകളും ചരിത്രങ്ങളും എപ്പോഴും കളിച്ചുകൊണ്ടിരിക്കുന്ന നാടകവേദി.....</h5></div>
      
    
      </div>
      </div>


<h2 class="mt-5">Portfolio</h2>
<hr>
<div class="row">
  {% for project in projects %}
  <div class="col-lg-4 col-md-6">

    {% if project.url %}
    <a href="{{ project.url }}">
      <img src="{{ project.image.url }}" class="img-fluid mb-2">
    </a>
    {% else %}

    <img src="{{ project.image.url }}" class="img-fluid mb-2">
    {% endif %}
    <h3>{{ project.title }}</h3>
    <p>{{ project.description }}</p>

  </div>
  {% endfor %}
  <div class="col-lg-4 col-md-6">
    <h3>Send me a Message</h3>
  <form method="POST">
    <label for="id_name">Name {{ form.name }}</label>
    <label for="id_email">Email {{ form.email }}</label>
    

    <label for="id_message">
    Message  <textarea name="message" id="id_message" required="" cols="40" rows="5" maxlength="100"></textarea>
 
    </label>
   
    {% csrf_token %}

  <input type="submit" class = 'btn btn-primary' value="Send">
  </form>
</div>
</div>

{% endblock %}

portfolio/templates/portfolio/new.html
{% extends "portfolio/base.html" %}
{% load static %}

{% block content %}
<br>
<br>
<div class="container" > 

<h2> I have received your message and will respond promptly. </h2>
<br>
Click <a href="{% url 'indexpage' %}" >here </a> to continue
</div>
{% endblock %}